name: geolocator_linux
description: Local Android-build stub for the Linux geolocator implementation.
version: 0.2.6
publish_to: 'none'

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator_platform_interface: ^4.2.8

flutter:
  plugin:
    implements: geolocator
    platforms:
      linux:
        dartPluginClass: GeolocatorLinux
