// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeZqlybc68Gl7rMdB8MRVhKCFbWDF2TUQ',
    appId: '1:420319876617:web:ac680e50f909b917744ad8',
    messagingSenderId: '420319876617',
    projectId: 'respondcrew',
    authDomain: 'respondcrew.firebaseapp.com',
    storageBucket: 'respondcrew.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22HeSfRpy9ftstqZ-uitPhC-FXQ94icY',
    appId: '1:420319876617:android:ec5320ae4ff9b34d744ad8',
    messagingSenderId: '420319876617',
    projectId: 'respondcrew',
    storageBucket: 'respondcrew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUUEmIYq8GP0tTg9hPerEDZAftSGnn1s',
    appId: '1:420319876617:ios:cdbfe1306fbcbbaf744ad8',
    messagingSenderId: '420319876617',
    projectId: 'respondcrew',
    storageBucket: 'respondcrew.firebasestorage.app',
    iosBundleId: 'com.example.respondcrewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuUUEmIYq8GP0tTg9hPerEDZAftSGnn1s',
    appId: '1:420319876617:ios:cdbfe1306fbcbbaf744ad8',
    messagingSenderId: '420319876617',
    projectId: 'respondcrew',
    storageBucket: 'respondcrew.firebasestorage.app',
    iosBundleId: 'com.example.respondcrewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeZqlybc68Gl7rMdB8MRVhKCFbWDF2TUQ',
    appId: '1:420319876617:web:0c877e8ebec501f1744ad8',
    messagingSenderId: '420319876617',
    projectId: 'respondcrew',
    authDomain: 'respondcrew.firebaseapp.com',
    storageBucket: 'respondcrew.firebasestorage.app',
  );
}
